version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=timetagger
      - POSTGRES_PASSWORD=timetagger
      - POSTGRES_DB=timetagger
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  timetagger:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - TIMETAGGER_BIND=${TIMETAGGER_BIND}
      - TIMETAGGER_LOG_LEVEL=${TIMETAGGER_LOG_LEVEL}
      - TIMETAGGER_CREDENTIALS=${TIMETAGGER_CREDENTIALS}
      - TIMETAGGER_DB_URL=postgresql://timetagger:timetagger@postgres:5432/timetagger
      # Microsoft Entra ID Configuration
      - TIMETAGGER_AZURE_CLIENT_ID=${TIMETAGGER_AZURE_CLIENT_ID}
      - TIMETAGGER_AZURE_TENANT_ID=${TIMETAGGER_AZURE_TENANT_ID}
      - TIMETAGGER_AZURE_CLIENT_SECRET=${TIMETAGGER_AZURE_CLIENT_SECRET}
      - TIMETAGGER_AZURE_INSTANCE=${TIMETAGGER_AZURE_INSTANCE}
      - TIMETAGGER_AZURE_REDIRECT_PATH=${TIMETAGGER_AZURE_REDIRECT_PATH}
      - TIMETAGGER_AZURE_REDIRECT_URI=${TIMETAGGER_AZURE_REDIRECT_URI}
      - TIMETAGGER_AZURE_SCOPES=${TIMETAGGER_AZURE_SCOPES}
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: 