version: '3.8'

services:
  # PostgreSQL database service
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=timetagger
      - POSTGRES_PASSWORD=timetagger  # Consider changing this in production
      - POSTGRES_DB=timetagger
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U timetagger"]
      interval: 10s
      timeout: 5s
      retries: 5

  # TimeTagger application
  timetagger:
    # Using forked repository from hsonixcode
    image: ghcr.io/hsonixcode/timetagger:latest
    # Alternative: Build from the forked repository
    # build: 
    #   context: https://github.com/hsonixcode/timetagger.git
    #   dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Only mount the data directory for persistence
      - timetagger_data:/app/data
    environment:
      - TIMETAGGER_BIND=0.0.0.0:8000
      - TIMETAGGER_LOG_LEVEL=info
      # Admin credentials in format "username:password"
      - TIMETAGGER_CREDENTIALS=admin:admin  # CHANGE THIS in production!
      # PostgreSQL connection
      - TIMETAGGER_DB_URL=postgresql://timetagger:timetagger@postgres:5432/timetagger
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    # This command ensures TimeTagger runs properly
    command: ["python", "-m", "timetagger"]

volumes:
  # Named volumes for data persistence
  postgres_data:
  timetagger_data: 